[profile.ci.fuzz]
runs = 10_000

[profile.default]
solc = "0.8.20"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 1_000
via_ir = true
bytecode_hash = "none"
fs_permissions = [{ access = "read-write", path = "./deployments/"}]

[rpc_endpoints]
anvil = "http://localhost:8546"

real = "${REAL_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum_one = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
base = "${BASE_RPC_URL}"

unreal = "${UNREAL_RPC_URL}"
polygon_mumbai = "${MUMBAI_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
polygon = { key = "${ETHERSCAN_POLYGON_KEY}" }
# real = { key = "", url = "https://real.blockscout.com/api" }
optimism = { key = "", url = "https://optimism.blockscout.com/api" }
base = { key = "", url = "https://base.blockscout.com/api" }

unreal = { key = "", url = "https://unreal.blockscout.com/api" }
mumbai = { key = "${ETHERSCAN_POLYGON_KEY}" }

[fmt]
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
